### ISSUE TITLE
Add more .ext files

### ISSUE THREAD

**Issue by codeleta** [fabiocaccamo/django-freeze#1]
scanner.py:111
replace
`if path.endswith('.html'):`
to
`if path.endswith('.html') or path.endswith('.xml') or path.endswith('.txt'):`

<a href="https://dashboard.polar.sh/fabiocaccamo/django-freeze/issues/1">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-freeze/issues/1/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-freeze/issues/1/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
Please, just explain me why you need this.

**Comment by Cotest** [comment]
add sitemap.xml and robots.txt to static site

**Comment by fabiocaccamo** [comment]
Fixed in `0.11.0` version.

**Comment by merwok** [comment]
FRI functions like `str.endswith`, `str.startswith` or `isinstance` accept a tuple for their second parameter!

**Comment by fabiocaccamo** [comment]
@merwok ohhh didn't know this for `str.startswith` and `str.endswith`, thank you!

**Comment by fabiocaccamo** [comment]
@merwok ba602fb
