### ISSUE TITLE
Extraneous new-line characters in output

### ISSUE THREAD

**Issue by keithcallenberg** [fabiocaccamo/django-freeze#19]
**Python version**
3.9.14

**Django version**
3.2.15

**Package version**
0.8.0

**Current behavior (bug description)**
Many extra new-line characters appear in the output that are not in the input.
![image](https://user-images.githubusercontent.com/999275/192674742-c73bf4fd-922b-4dfb-95ff-7c70b823f7a1.png)

**Expected behavior**
They should not be there.

<a href="https://dashboard.polar.sh/fabiocaccamo/django-freeze/issues/19">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-freeze/issues/19/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-freeze/issues/19/pledge.svg">
</picture>
</a>

**Comment by keithcallenberg** [comment]
I commented out Line 112 of scanner.py and the problem went away:
https://github.com/fabiocaccamo/django-freeze/blob/master/freeze/scanner.py#L112

![image](https://user-images.githubusercontent.com/999275/192680269-5af171e1-71ea-4131-9f84-66eabc01e56d.png)

**Comment by fabiocaccamo** [comment]
@keithcallenberg thank you for reporting this, could you provide your html please?
It's time to add tests to this library.

**Comment by fabiocaccamo** [comment]
@keithcallenberg any feedback?
