### ISSUE TITLE
Support for Django 1.11 (LTS)?

### ISSUE THREAD

**Issue by ipsod** [fabiocaccamo/django-freeze#8]
Do you have any plans to support this latest LTS release?

**Comment by fabiocaccamo** [comment]
Actually I'm not using `django-freeze` in any project. 
This lib would need a test suite to support new django versions with backward compatibility, but I've not time do write tests, I could just create the main test suite and add tox and travis if someone can write tests.

**Comment by fabiocaccamo** [comment]
@ipsod I published a `0.7.0` release.
